import type { Metadata } from "next";
import "./globals.css";
import { DotPattern } from "@/components/magicui/dot-pattern";
import { NavBar } from "@/components/ui/tubelight-navbar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <DotPattern width={32} height={32} />
        {children}
      </body>
    </html>
  );
}
